const englishWords = {
    kolay: [
        // Unit 1-3
        { tr: "ambulans", en: "ambulance" },
        { tr: "balon", en: "balloon" },
        { tr: "bisküvi", en: "biscuit" },
        { tr: "kafe", en: "café" },
        { tr: "pasta", en: "cake" },
        { tr: "kamp", en: "camp" },
        { tr: "doktor", en: "doctor" },
        { tr: "e-posta", en: "e-mail" },
        { tr: "elektrik", en: "electrics" },
        { tr: "garaj", en: "garage" },
        { tr: "otel", en: "hotel" },
        { tr: "internet", en: "Internet" },
        { tr: "dizüstü bilgisayar", en: "laptop" },
        { tr: "limon", en: "lemon" },
        { tr: "mikrofon", en: "microphone" },
        { tr: "not", en: "note" },
        { tr: "ofis", en: "office" },
        { tr: "piknik", en: "picnic" },
        { tr: "sınav", en: "quiz" },
        { tr: "radyo", en: "radio" },
        { tr: "salata", en: "salad" },
        { tr: "sandviç", en: "sandwich" },
        { tr: "spor", en: "sport" },
        { tr: "dur", en: "stop" },
        { tr: "süpermarket", en: "supermarket" },
        { tr: "telefon", en: "telephone" },
        { tr: "televizyon", en: "television" },
        { tr: "domates", en: "tomato" },
        { tr: "tren", en: "train" },
        { tr: "kelime", en: "word" },
        { tr: "üniversite", en: "university" },
        { tr: "vanilya", en: "vanilla" },
        { tr: "video", en: "video" },
        { tr: "yoğurt", en: "yoghurt" },
        // Selamlaşma ve tanışma
        { tr: "günaydın", en: "good morning" },
        { tr: "iyi günler", en: "good afternoon" },
        { tr: "iyi akşamlar", en: "good evening" },
        { tr: "iyi geceler", en: "good night" },
        { tr: "merhaba", en: "hello" },
        { tr: "selam", en: "hi" },
        { tr: "hoşçakal", en: "goodbye" },
        { tr: "nasılsın", en: "how are you" },
        { tr: "adın ne", en: "what's your name" },
        { tr: "ben (isim)", en: "I'm (name)" },
        { tr: "tanıştığıma memnun oldum", en: "nice to meet you" },
        // Sınıf içi komutlar
        { tr: "aç", en: "open" },
        { tr: "kapat", en: "close" },
        { tr: "kes", en: "cut" },
        { tr: "çiz", en: "draw" },
        { tr: "boya", en: "paint" },
        { tr: "söyle", en: "say" },
        { tr: "otur", en: "sit" },
        { tr: "yapıştır", en: "stick" },
        { tr: "ayağa kalk", en: "stand" },
        { tr: "çevir", en: "turn" }
    ],
    orta: [
        // Sayılar
        { tr: "bir", en: "one" },
        { tr: "iki", en: "two" },
        { tr: "üç", en: "three" },
        { tr: "dört", en: "four" },
        { tr: "beş", en: "five" },
        { tr: "altı", en: "six" },
        { tr: "yedi", en: "seven" },
        { tr: "sekiz", en: "eight" },
        { tr: "dokuz", en: "nine" },
        { tr: "on", en: "ten" },
        { tr: "on bir", en: "eleven" },
        { tr: "on iki", en: "twelve" },
        { tr: "on üç", en: "thirteen" },
        { tr: "on dört", en: "fourteen" },
        { tr: "on beş", en: "fifteen" },
        { tr: "on altı", en: "sixteen" },
        { tr: "on yedi", en: "seventeen" },
        { tr: "on sekiz", en: "eighteen" },
        { tr: "on dokuz", en: "nineteen" },
        { tr: "yirmi", en: "twenty" },
        // Renkler
        { tr: "siyah", en: "black" },
        { tr: "mavi", en: "blue" },
        { tr: "kahverengi", en: "brown" },
        { tr: "yeşil", en: "green" },
        { tr: "turuncu", en: "orange" },
        { tr: "pembe", en: "pink" },
        { tr: "mor", en: "purple" },
        { tr: "kırmızı", en: "red" },
        { tr: "beyaz", en: "white" },
        { tr: "sarı", en: "yellow" },
        // Oyun alanında
        { tr: "top", en: "ball" },
        { tr: "bisiklet", en: "bike" },
        { tr: "tırman", en: "climb" },
        { tr: "dans et", en: "dance" },
        { tr: "uç", en: "fly" },
        { tr: "saklan", en: "hide" },
        { tr: "zıpla", en: "hop" },
        { tr: "atla", en: "jump" },
        { tr: "tekme at", en: "kick" },
        { tr: "oyna", en: "play" },
        { tr: "sür", en: "ride" },
        { tr: "koş", en: "run" },
        { tr: "kay", en: "slide" },
        { tr: "sallan", en: "swing" },
        // Vücut Bölümleri
        { tr: "kol", en: "arm" },
        { tr: "kulak", en: "ear" },
        { tr: "göz", en: "eye" },
        { tr: "yüz", en: "face" },
        { tr: "parmak", en: "finger" },
        { tr: "ayak", en: "foot" },
        { tr: "saç", en: "hair" },
        { tr: "el", en: "hand" },
        { tr: "baş", en: "head" },
        { tr: "diz", en: "knee" },
        { tr: "bacak", en: "leg" },
        { tr: "ağız", en: "mouth" },
        { tr: "burun", en: "nose" },
        { tr: "omuz", en: "shoulder" },
        { tr: "ayak parmağı", en: "toe" }
    ],
    zor: [
        // Evcil Hayvanlar
        { tr: "kuş", en: "bird" },
        { tr: "kedi", en: "cat" },
        { tr: "köpek", en: "dog" },
        { tr: "balık", en: "fish" },
        { tr: "hamster", en: "hamster" },
        { tr: "fare", en: "mouse" },
        { tr: "papağan", en: "parrot" },
        { tr: "tavşan", en: "rabbit" },
        { tr: "yılan", en: "snake" },
        { tr: "kaplumbağa", en: "turtle" },
        // Meyveler
        { tr: "elma", en: "apple" },
        { tr: "muz", en: "banana" },
        { tr: "üzüm", en: "grape" },
        { tr: "kivi", en: "kiwi" },
        { tr: "limon", en: "lemon" },
        { tr: "portakal", en: "orange" },
        { tr: "şeftali", en: "peach" },
        { tr: "armut", en: "pear" },
        { tr: "ananas", en: "pineapple" },
        { tr: "erik", en: "plum" },
        { tr: "çilek", en: "strawberry" },
        { tr: "karpuz", en: "watermelon" },
        // Vahşi Hayvanlar
        { tr: "ayı", en: "bear" },
        { tr: "fil", en: "elephant" },
        { tr: "zürafa", en: "giraffe" },
        { tr: "goril", en: "gorilla" },
        { tr: "kanguru", en: "kangaroo" },
        { tr: "aslan", en: "lion" },
        { tr: "maymun", en: "monkey" },
        { tr: "panda", en: "panda" },
        { tr: "kaplan", en: "tiger" },
        { tr: "zebra", en: "zebra" }
    ]
}; 